# Generated by Django 3.2 on 2021-06-13 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('scale', models.IntegerField(verbose_name='Возраст')),
                ('pol', models.CharField(choices=[('W', 'Женский'), ('M', 'Мужской')], max_length=1, verbose_name='Пол')),
                ('number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=150, verbose_name='Почта')),
                ('bran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branches')),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
