# Generated by Django 3.2 on 2021-06-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название программы')),
                ('description', models.CharField(max_length=300, verbose_name='Описание программы')),
                ('text', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='program/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
    ]
