# Generated by Django 3.2 on 2021-06-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='title',
            new_name='name',
        ),
    ]
