# Generated by Django 3.2 on 2021-06-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_rename_title_price_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='name',
            new_name='title',
        ),
    ]
